# Generated by Django 4.2.2 on 2023-07-17 01:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("aluno", "0002_rename_matricula_aluno"),
    ]

    operations = [
        migrations.RenameField(
            model_name="cidade",
            old_name="nome",
            new_name="nome_cidade",
        ),
        migrations.RenameField(
            model_name="curso",
            old_name="nome",
            new_name="nome_curso",
        ),
    ]
